"""sync from DB metadata

Revision ID: 4a745f556c76
Revises: 9fa13cef666a
Create Date: 2025-12-01 07:07:01.734620

"""
from pgvector.sqlalchemy import Vector

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a745f556c76'
down_revision: Union[str, Sequence[str], None] = '9fa13cef666a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_requests', sa.Column('audio_url', sa.String(length=500), nullable=True))
    op.add_column('ad_requests', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.alter_column('ad_requests', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('ad_requests', 'deleted_at')

    # TEXT → VECTOR 변환 (연동 SQL)
    op.execute(
        "ALTER TABLE user_memories "
        "ALTER COLUMN embedding "
        "TYPE VECTOR(1536) "
        "USING (embedding::VECTOR(1536));"
    )

    op.alter_column('user_memories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_memories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('user_memories', 'deleted_at')

    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    op.add_column('user_memories', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # VECTOR → TEXT 되돌리기
    op.execute(
        "ALTER TABLE user_memories "
        "ALTER COLUMN embedding "
        "TYPE TEXT "
        "USING (embedding::text);"
    )

    op.alter_column('user_memories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_memories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.add_column('ad_requests', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('ad_requests', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('ad_requests', 'video_url')
    op.drop_column('ad_requests', 'audio_url')
    # ### end Alembic commands ###
