"""add bgm_prompt to ad_requests

Revision ID: e779a5ca17e0
Revises: 4a745f556c76
Create Date: 2025-12-03 03:12:19.498151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e779a5ca17e0'
down_revision: Union[str, Sequence[str], None] = '4a745f556c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_requests', sa.Column('bgm_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_requests', 'bgm_prompt')
    # ### end Alembic commands ###
